config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update]
  resources :events, only: [:show, :create, :edit, :update, :destroy]

  root 'home#top'
  get '/about' => 'home#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true, length: {maximum: 140}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events

  validates :name, presence: true

  def set_image(file)
    if !file.nil?
      file_name = file.original_filename
      File.open("public/user_images/#{file_name}", 'wb'){|f| f.write(file.read)}
      self.image = file_name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  include ApplicationHelper

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to @event, notice: "Successfully created"
    else
      @events = Event.all.order(created_at: :desc)
      render 'home/top'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: "success"
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private

    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :description)
    end

    def correct_user
      event = Event.find(params[:id])

      if !current_user?(event.user)
        redirect_to root_path, alert: "The page you've tried to visit is not allowed"
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
    if user_signed_in?
      @event = Event.new
      @events = Event.all.order(created_at: :desc)
    else
      @message = "Welcome to Circle!"
    end
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  before_action :set_user, only: [:show, :edit, :update]


  def index
    @users = User.all
  end

  def show
    @events = @user.events
  end

  def edit
  end

  def update
    file = params[:user][:image]
    @user.set_image(file)

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email)
    end

    def correct_user
      user = User.find(params[:id])

      if current_user.id != user.id
        redirect_to root_path, alert: "The page you've tried to visit is not allowed"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user?(user)
    current_user.id == user.id
  end

  def check_image?(user)
    user.id
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper


  def image_for(user)
    # user = current_user
    if user.image
      image_tag "/user_images/#{user.image}", class: "profile_img"
    else
      image_tag "default_profile.png", class: "profile_img"
    end
  end

end

app/views/events/_event.html.erb
<li>
  <%= image_for(event.user) %>
  <span class="user-name">
    <%= event.user.name %>
  </span>
  <span class="content">
    <%= link_to event.title, event_path(event.id) %>
  </span>
  <span>
    <%= event.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
  </span>
</li>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @event.errors.count %>errors</h2>

      <ul>
        <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  Title
  <%= f.text_field :title, class: "form-control title-field" %>
  Description
  <%= f.text_area :description, class: "form-control content-field" %>
  <%= f.submit 'Save', class: 'btn primary-btn' %>

<% end %>

app/views/events/edit.html.erb
<h1>Edit the event</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1>List of events</h1>
<ul class="events">
  <%= render @events %>
</ul>

app/views/events/new.html.erb
<h1>Create an event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<p id="notice" class="alert alert-success">
  <%= notice %>
</p>

<h2>Title</h2>
<p><%= @event.title %></p>
<h2>description</h2>
<p><%= @event.description %></p>

<% if current_user?(@event.user) %>
  <%= link_to "Edit", edit_event_path(@event.id), class: 'btn edit-btn' %>
  <%= link_to "Delete", event_path(@event.id), method: "delete", class: "btn destroy-btn", "data-confirm" => "Are you sure you want to delete it?" %>
<% end %>

app/views/home/about.html.erb
<h1>What you can do is...</h1>
<p>Connect with people like a circle!</p>

app/views/home/top.html.erb
<% if user_signed_in? %>
  <aside class="sidebar">
    <%= render 'events/form' %>
  </aside>
  <ul class="notes">
    <h2>List of events</h2>
    <%= render @events %>
  </ul>
<% else %>
  <div class="top-wrapper">
    <%= image_tag "logo.png" %>
    <div class="register-wrapper">
      <h1><%= @message %></h1>
      <%= link_to "Signup", new_user_registration_path, class: "btn btn-large register-btn" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Circle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel='stylesheet' href='fullcalendar/fullcalendar.css' />
    <script src='lib/jquery.min.js'></script>
    <script src='lib/moment.min.js'></script>
    <script src='fullcalendar/fullcalendar.js'></script>
  </head>

  <body>
    <script>
      $(document).ready(function() {

  // page is now ready, initialize the calendar...

        $('#calendar').fullCalendar({
      // put your options and callbacks here
        })

      });
    </script>

    <header class="navbar">
      <div class="container">
        <div id="logo"><%= link_to "Circle", root_path %></div>
        <% if user_signed_in? %>
          <ul class="header-right">
            <li><%= link_to "List of Users", users_path %></li>
            <li><%= link_to current_user.email, current_user %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% else %>
          <ul class="header-right">
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "SignUp now", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          </ul>
        <% end %>
      </div>
    </header>

    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>

    <div class="container">
      <footer class="footer">
        <div class="small">
          &copy; 2017 Circle, Inc.
        </div>
      </footer>
    </div>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
       <p><%= @user.errors.count %>件のエラーがあります。</p>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  name
  <%= f.text_field :name, class: "form-control name-field" %>

  Email
  <%= f.text_field :email, class: "form-control email-field" %>

  Profile Pic
  <%= f.file_field :image, class: "form-control image-field" %>
  <%= f.submit 'Save', class: "btn primary-btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1 class="heading">List of Users</h1>

<ul class="user-list">
  <% @users.each do |user| %>
    <li>
      <%= image_for(user) %>
      <%= link_to user.name, user %>
      <%= user.email %>
    </li>
  <% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice" class="alert alert-success"><%= notice %></p>

<aside class="sidebar">
  <section>
    <!-- <span class="label">Profile Pic</span> -->
    <h3 class="user-info">
      <%= image_for(@user) %>
    </h3>
  </section>

  <section>
    <span class="label">User</span>
    <h3 class="user-info"><%= @user.name %></h3>
  </section>

  <!--
  <section>
    <span class="label">Email</span>
    <h3 class="user-info"><%= @user.email %></h3>
  </section>
  -->

  <% if current_user?(@user) %>
    <section>
      <small><%= link_to 'Edit profile', edit_user_path(@user) %></small>
    </section>
  <% end %>

</aside>

<ul class="events">
  <%= render @events %>
</ul>

<div id="calendar"></div>